ora12c:
  container_name: ora12c
  build:
    .
  dockerfile:
    Dockerfile
  environment:
    - DBCA_TOTAL_MEMORY=1024
    - DUMP_INIT_SQL=init.sql
    - DUMP_USER=test_dpump
    - DUMP_PASSWORD=test
    - DUMP_FILE=test.dmp
  ports:
    - "8080:8080"
    - "1521:1521" 