ora12c:
  container_name: ora12c
  build:
    .
  dockerfile:
    Dockerfile
  environment:
    - DBCA_TOTAL_MEMORY=1024
    - DUMP_INIT_SQL=init.sql
    - DUMP_USER=DFOX
    - DUMP_PASSWORD=developer
    - DUMP_FILE=dump_after_migration_fresh_config_v4.dmp
  ports:
    - "8080:8080"
    - "1521:1521" 