CREATE USER c##DFOX IDENTIFIED BY developer;

ALTER USER c##DFOX IDENTIFIED BY developer ACCOUNT UNLOCK;

GRANT ALL PRIVILEGES TO c##DFOX;
GRANT CREATE ANY DIRECTORY TO c##DFOX;
GRANT CREATE SESSION TO c##DFOX;
GRANT CREATE TABLE TO c##DFOX;
GRANT CREATE TABLESPACE TO c##DFOX;

CREATE TABLESPACE FOXDATA DATAFILE '/u01/app/oracle/oradata/XE/FOXDATA.DBF' SIZE 400M;
ALTER TABLESPACE SYSTEM ADD DATAFILE '/u01/app/oracle/oradata/XE/SYSTEM02.DBF' SIZE 400M;
ALTER TABLESPACE SYSTEM ADD DATAFILE '/u01/app/oracle/oradata/XE/SYSTEM03.DBF' SIZE 400M;
ALTER TABLESPACE SYSAUX ADD DATAFILE '/u01/app/oracle/oradata/XE/SYSAUX002.DBF' SIZE 400M;

CREATE OR REPLACE DIRECTORY dump_dir AS '/usr/local/oracle/dumps/';

GRANT READ, WRITE ON DIRECTORY dump_dir TO c##DFOX;

